# .github/workflows/python-publish-pypi.yml

name: Upload to PyPI

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: pypi-github-sync
      uses: PabloLec/pypi-github-sync@v1.0.1
      with:
        github_repo: haiiliin/pyqtribbon
        twine_username: ${{ secrets.TWINE_USERNAME }}
        twine_password: ${{ secrets.TWINE_PASSWORD }}
